BBPATH .= ":${LAYERDIR}"

BBFILES += "\
    ${LAYERDIR}/recipes-*/*/*.bb \
    ${LAYERDIR}/recipes-*/*/*.bbappend \
"

BBFILE_COLLECTIONS += "elk"
BBFILE_PATTERN_elk = "^${LAYERDIR}/"
BBFILE_PRIORITY_elk = "8"
LAYERDEPENDS = "qt5"
LAYERSERIES_COMPAT_elk = "kirkstone scarthgap"
#BBMASK += "meta-elk/recipes-binaries/sushi/sushi_git.bb"
#BBMASK += "meta-elk/recipes-binaries/sensei/sensei_git.bb"
BBMASK += "meta-elk/recipes-qt/simple-qt/simple-qt_0.1.bb"
BBMASK += "meta-elk/recipes-devtools/abseil-cpp/abseil-cpp_git.bbappend"
BBMASK += "meta-elk/recipes-devtools/clang/clang_git.bbappend"
BBMASK += "meta-elk/recipes-qt/qt/qtbase_git.bbappend"

