#!/bin/sh

# Buffer size is provided systemwide  by elk-system.conf
ELK_SYSTEM_CONF="/udata/.elk-system/elk-system.conf"
if [ -e $ELK_SYSTEM_CONF ]; then
    source $ELK_SYSTEM_CONF
else
    echo "No elk-system.conf file found ! Unable to get audio buffer size info."
    exit 1
fi

# Select the right sushi binary depening on AUDIO_BUFFER_SIZE
SUSHI_BINARY=sushi_b$AUDIO_BUFFER_SIZE
SUSHI_ARGS=${@}

exec -a sushi $SUSHI_BINARY $SUSHI_ARGS

